const sonarqubeScanner = require('sonarqube-scanner');

sonarqubeScanner({
  serverUrl: 'http://192.168.1.5:9000/',
       options : {
	    'sonar.projectDescription': 'This is a Node JS application',
	    'sonar.projectName': 'Node JS Application - Sample',
	    'sonar.projectKey':'NodeJsMithunTechnologies',
	    'sonar.login': '92b64a4c798abcfff5b994a4a66fac85c7762e60',
	    //'sonar.login': 'admin',
	    //'sonar.password': 'admin',
	       //'sonar.login': 'admin',
	    //'sonar.password': 'admin',
	       //'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',//'sonar.login': 'admin',
	    //'sonar.password': 'admin',
            'sonar.projectVersion':'1.0',
	    'sonar.language':'js',
            'sonar.sourceEncoding':'UTF-8',
            'sonar.sources': '.',
	  //'sonar.tests': 'specs',
          //'sonar.inclusions' : 'src/**'
       },
}, () => {});
